//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ue4ModuleCreator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ue4ModuleCreator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the project folder of your Unreal Engine 4 project..
        /// </summary>
        internal static string MainForm_projectPathFolderBrowserDescription {
            get {
                return ResourceManager.GetString("MainForm_projectPathFolderBrowserDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %COPYRIGHT%
        ///
        ///using UnrealBuildTool;
        ///
        ///public class %MODULENAME% : ModuleRules
        ///{
        ///    public %MODULENAME%(ReadOnlyTargetRules Target) : base(Target)
        ///    {
        ///        PCHUsage = ModuleRules.PCHUsageMode.UseExplicitOrSharedPCHs;
        ///
        ///        PublicIncludePaths.AddRange(
        ///            new string[] {
        ///                &quot;%MODULENAME%/Public&quot;
        ///                // ... add public include paths required here ...
        ///            }
        ///        );
        ///
        ///
        ///        PrivateIncludePaths.AddRange(
        ///            new string[] {
        ///           [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string moduleCreator_buildCs {
            get {
                return ResourceManager.GetString("moduleCreator_buildCs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //Autogenerated by ue4ModuleCreator
        /////https://github.com/okanag/unrealModuleCreator.
        /// </summary>
        internal static string moduleCreator_copyright {
            get {
                return ResourceManager.GetString("moduleCreator_copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %COPYRIGHT%
        ///
        ///#pragma once
        ///
        ///#include &quot;CoreMinimal.h&quot;
        ///#include &quot;ModuleManager.h&quot;
        ///
        ///
        ///class F%MODULENAME%Module : public IModuleInterface
        ///{
        ///public:
        ///	virtual void StartupModule() override;
        ///	virtual void ShutdownModule() override;
        ///};.
        /// </summary>
        internal static string moduleCreator_moduleHeader {
            get {
                return ResourceManager.GetString("moduleCreator_moduleHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %COPYRIGHT%
        ///
        ///#include &quot;%MODULENAME%.h&quot;
        ///
        ///
        ///void F%MODULENAME%Module::StartupModule()
        ///{
        ///}
        ///
        ///void F%MODULENAME%Module::ShutdownModule()
        ///{
        ///}
        ///
        ///IMPLEMENT_MODULE(F%MODULENAME%Module, %MODULENAME%);.
        /// </summary>
        internal static string moduleCreator_moduleSource {
            get {
                return ResourceManager.GetString("moduleCreator_moduleSource", resourceCulture);
            }
        }
    }
}
